name: install
description: 'Set yarn version and install'

runs:
  using: composite
  steps:
    - name: install node
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.1'
    - run: corepack enable
      shell: bash
    - run: corepack prepare yarn@4.1.1 --activate
      shell: bash
    - run: yarn set version 4.1.1
      shell: bash
    - name: yarn install
      uses: ./.github/actions/yarn-nm-install
      with:
        enable-corepack: false
        cache-install-state: true
        cache-node-modules: true
